# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
node: circleci/node@4.7

jobs:
  build:
    docker:
      - image: cimg/node:12.22
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run install
          command: npm run lint
      - save_cache:
          key: "npm-packages"
          paths:
            - /src/node_modules

  test:
    docker:
      - image: cimg/node:12.22
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run tests
          command: npm run test

  analyze:
    docker:
      - image: cimg/node:12.22
    steps:
      - checkout
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run audit
          command: npm run audit


workflows:
  sample:
    jobs:
      - build
      - test
        requires:
          - build
      - analyze
        requires:
          - test
